[Datasets]
data_dir : data/
train_prefix : mammalian_200-1200_train_balanced
val_prefix : mammalian_200-1200_val_nonredundant_80
test_prefix : mammalian_200-1200_test_nonredundant_80
[Best Models]
best_BIO_DIR : experiments/output/bioseq2seq_CNN_3_Jul02_19-50-23_step_11000/
best_EDC_DIR : experiments/output/bioseq2seq_CNN_3_Jul02_19-50-23_step_11000/
best_BIO_chkpt : experiments/checkpoints/coding_noncoding/bioseq2seq_CNN_3_Jul02_19-50-23/_step_11000.pt
best_EDC_chkpt : experiments/checkpoints/coding_noncoding/bioseq2seq_CNN_3_Jul02_19-50-23/_step_11000.pt
all_BIO_replicates : experiments/scripts/txt/cnn_models.txt
all_EDC_replicates : experiments/scripts/txt/cnn_models.txt
all_EDC_small_replicates : experiments/scripts/txt/top1_EDC-small_models.txt
[Encoder-Decoder Attention]
best_BIO_EDA : {'model':'bioseq2seq','attr' : 'EDA','n_layers' : 2}
best_EDC_EDA : {'model':'EDC','attr' : 'EDA','n_layers' : 16}
[Attributions]
reference_class : PC
position : 1

