[Datasets]
train_csv : data/mammalian_200-1200_train_balanced.csv
val_csv : data/mammalian_200-1200_val_nonredundant_80.csv
test_csv : data/mammalian_200-1200_test_nonredundant_80.csv
[Results]
competitors_results : competitors_results.txt
bioseq2seq_results : translation_scores.txt
EDC_results : tmp.txt
[Self-Attention]
best_seq_self_attn : best_seq2seq.self_attn
best_EDC_self_attn : best_EDC.self_attn
[Encoder-Decoder Attention]
best_BIO_EDA : {'model' : 'bioseq2seq', 'attr' : 'EDA','prefix' : 'experiments/output/bioseq2seq_4_test/enc_dec_attns_layer','suffix' : '.npz','layers' : [0,1]}
best_EDC_EDA : {'model' : 'EDC', 'attr' : 'EDA','prefix' : 'experiments/output/EDC_large_1_test','suffix' : '.enc_dec_attns','layers' : [0,1]}
[Gradients]
best_BIO_grad : 'experiments/output/bioseq2seq_4_test/all.NC.inputXgrad.npz'
best_EDC_grad : {'model' : 'EDC', 'attr' : 'IG','prefix' : 'experiments/output/EDC_1_val','suffix' : '_pos_test.ig','bases' : ['avg','zero']}
