bash experiments/scripts/demo.sh small MDIG PC 1
#bash experiments/scripts/demo.sh small MDIG NC 1
#bash experiments/scripts/demo.sh small grad PC 1
#bash experiments/scripts/demo.sh small grad NC 1
#bash experiments/scripts/demo.sh small MDIG STOP 10
#bash experiments/scripts/demo.sh small grad STOP 10
#python experiments/analysis/plot_examples.py small MDIG PC 1
#python experiments/analysis/plot_examples.py small MDIG NC 1
#python experiments/analysis/plot_examples.py small grad PC 1
#python experiments/analysis/plot_examples.py small grad NC 1
#python experiments/analysis/plot_examples.py small MDIG STOP 10
#python experiments/analysis/plot_examples.py small grad STOP 10
