#!/usr/bin/env bash
export BIOHOME=/home/bb/valejose/home
export PYTHONPATH=/home/bb/valejose/home/bioseq2seq
source $BIOHOME/bioseq2seq/venv/bin/activate
#python $BIOHOME/bioseq2seq/bioseq2seq/bin/integrated_gradients.py --input $BIOHOME/bioseq2seq/data/mammalian_1k_test_nonredundant_80.csv --checkpoint $BIOHOME/bioseq2seq/checkpoints/coding_noncoding/Oct12_15-42-19/_step_150000.pt --name EDC_3_zero_pos_test --rank 0 --num_gpus 4 --attribution_mode ig  --baseline zero
#python $BIOHOME/bioseq2seq/bioseq2seq/bin/integrated_gradients.py --input $BIOHOME/bioseq2seq/data/mammalian_1k_test_nonredundant_80.csv --checkpoint $BIOHOME/bioseq2seq/checkpoints/coding_noncoding/Oct12_15-42-19/_step_150000.pt --name EDC_3_avg_pos_test --rank 0 --num_gpus 4 --attribution_mode ig  --baseline avg
#python $BIOHOME/bioseq2seq/bioseq2seq/bin/integrated_gradients.py --input $BIOHOME/bioseq2seq/data/mammalian_1k_test_nonredundant_80.csv --checkpoint $BIOHOME/bioseq2seq/checkpoints/coding_noncoding/Oct12_15-42-19/_step_150000.pt --name EDC_3_A_pos_test --rank 0 --num_gpus 4 --attribution_mode ig  --baseline A
python $BIOHOME/bioseq2seq/bioseq2seq/bin/integrated_gradients.py --input $BIOHOME/bioseq2seq/data/mammalian_1k_test_nonredundant_80.csv --checkpoint $BIOHOME/bioseq2seq/checkpoints/coding_noncoding/Oct12_15-42-19/_step_150000.pt --name EDC_3_C_pos_test --rank 0 --num_gpus 4 --attribution_mode ig  --baseline C
python $BIOHOME/bioseq2seq/bioseq2seq/bin/integrated_gradients.py --input $BIOHOME/bioseq2seq/data/mammalian_1k_test_nonredundant_80.csv --checkpoint $BIOHOME/bioseq2seq/checkpoints/coding_noncoding/Oct12_15-42-19/_step_150000.pt --name EDC_3_G_pos_test --rank 0 --num_gpus 4 --attribution_mode ig  --baseline G
python $BIOHOME/bioseq2seq/bioseq2seq/bin/integrated_gradients.py --input $BIOHOME/bioseq2seq/data/mammalian_1k_test_nonredundant_80.csv --checkpoint $BIOHOME/bioseq2seq/checkpoints/coding_noncoding/Oct12_15-42-19/_step_150000.pt --name EDC_3_T_pos_test --rank 0 --num_gpus 4 --attribution_mode ig  --baseline T
